,e,r,i,n,g=load,pcall,string,gsub,rawget,require,next,type
local function encrypt(str)local r=""for i=1,#str do local b=s.byte(str,i)r=r..s.format("%02X",b)end return r end
local function decrypt(str)local r=""for i=1,#str,2 do local b=s.sub(str,i,i+1)r=r..s.char(tonumber(b,16))end return r en
local player=game:service'Players'.LocalPlayer,camera=workspace:service'CurrentCamera',rs=game:service'RunService',ts=game:service'TweenService',uis=game:service'UserInputService'
local aimbotActive=true,lockedTarget=nil,currentSpeed=50,currentJump=100,targetImageLabel=nil
local function getAvatar(uid)return"https://www.roblox.com/headshot-thumbnail/image?userId="..uid.."&width=150&height=150"end
local function isEnemy(p)if p==player or not p.Character or not p.Character:FindFirstChild'Humanoid'or p.Character.Humanoid.Health<=0 or(player.Team and p.Team and player.Team==p.Team)then return false end return true endlayer(part)local lp=s.lower(part)for _,p in pairs(game.Players:GetPlayers())do if s.find(s.lower(p.Name),lp,1,true)or s.find(s.lower(p.DisplayName or""),lp,1,true)then return p end end return nil end
local function getTarget()if lockedTarget and lockedTarget.Character and lockedTarget.Character:FindFirstChild'Head'and isEnemy(lockedTarget)then return lockedTarget.Character.Head else if lockedTarget then game:service'StarterGui':SetCore("SendNotification',{Title="🚫 هدف خرج",Text=lockedTarget.Name.." مات أو غادر",Duration=3})lockedTarget=nil if targetImageLabel then targetImageLabel.Image="rbxassetid://0"end end local cd,ch=400,nil local mp=Vector2.new(player:GetMouse().X,player:GetMouse().Y)for _,p in pairs(game.Players:GetPlayers())do if isEnemy(p)and p.Character and p.Character:FindFirstChild'Head'then local pos,onS=camera:WorldToScreenPoint(p.Character.Head.Position)if onS then local d=(Vector2.new(pos.X,pos.Y)-mp).Magnitude if d<cd then cd=d ch=p.Character.Head end end end end return ch end end
rs.RenderStepped:Connect(function()if aimbotActive then local t=getTarget()if t then local dir=(t.Position-camera.CFrame.Position).Unit camera.CFrame=CFrame.lookAt(camera.CFrame.Position,camera.CFrame.Position+dir)end end end)
local function apply()if player.Character and player.Character:FindFirstChild'Humanoid'then player.Character. local tp=lockedTarget.Character.HumanoidRootPart.Position if player.Character and player.Character:FindFirstChild'HumanoidRootPart'then player.Character.HumanoidRootPart.CFrame=CFrame.new(tp+Vector3.new(0,3,0))game:service'StarterGui':SetCore("SendNotification",{Title="✨ تنقل",Text="تم الانتقال إلى "..lockedTarget.Name,Duration=2})end else game:service'StarterGui':SetCore("SendNotification",{Title="⚠️ خطأ",Text="لا يوجد هدف مقفول",Duration=2})end end
local function walk()if lockedTarget and lockedTarget.Character and lockedTarget.Character:FindFirstChild'HumanoidRootPart'and player.Character then local hum=player.Character:FindFirstChild'Humanoid'if hum then local tp=lockedTarget.Character.HumanoidRootPart.Position local d=(tp-player.Character.HumanoidRootPart.Position).Magnitude local ti=TweenInfo.new(d/(hum.WalkSpeed+10),Enum.EasingStyle.Linear)ts:Create(player.Character.HumanoidRootPart,ti,{CFrame=CFrame.new(tp+Vector3.new(0,3,0))}):Play()game:service'StarterGui':SetCore("SendNotification",{Title="🚶 سير",Text="جارٍ التوجه إلى "..lockedTarget.Name,Duration=2})end else game:service'StarterGui':SetCore("SendNotification",{Title="⚠️ خطأ",Text="لا يمكن السير للهدف",Duration=2})end end
local gui=Instance.new'ScreenGui'gui.Name="AYF_SCRIPT"gui.ResetOnSpawn=false gui.Parent=player:FindFirstChild'PlayerGui'or game:service'CoreGui'
local main=Instance.new'Frame'main.Size=UDim2.new(0,380,0,480)main.Position=UDim2.new(.5,-190,.5,-240)main.BackgroundColor3=Color3.new(0,0,0)main.BackgroundTransparency=.15 main.BorderSizePixel=3 main.BorderColor3=Color3.new(0,1,0)main.Visible=false main.Active=true main.Parent=gui
local tb=Instance.new'Frame'tb.Size=UDim2.new(1,0,0,40)tb.BackgroundColor3=Color3.new(0,.1,0)tb.BorderSizePixel=0 tb.Parent=main
local tl=Instance.new'TextLabel'tl.Size=UDim2.new(1,-50,1,0)tl.Position=UDim2.new(0,10,0,0)tl.BackgroundTransparency=1 tl.Text="💚 AYF SCRIPT 💚"tl.TextColor3=Color3.new(0,1,0)tl.TextScaled=true tl.Font=Enum.Font.GothamBold tl.Parent=tb
local cb=Instance.new'TextButton'cb.Size=UDim2.new(0,40,1,0)cb.Position=UDim2.new(1,-40,0,0)cb.BackgroundColor3=Color3.new(.2,0,0)cb.BorderSizePixel=1 cb.BorderColor3=Color3.new(1,0,0)cb.Text="✕"cb.TextColor3=Color3.new(1,0,0)cb.TextScaled=true cb.Font=Enum.Font.GothamBold cb.Parent=tb cb.MouseButton1Click:Connect(function()main.Visible=false end)
local tCon=Instance.new'Frame'tCon.Size=UDim2.new(1,0,0,40)tCon.Position=UDim2.new(0,0,0,40)tCon.BackgroundColor3=Color3.new(.05,.05,.05)tCon.BorderSizePixel=1 tCon.BorderColor3=Color3.new(0,.4,0)tCon.Parent=main
local cCon=Instance.new'Frame'cCon.Size=UDim2.new(1,0,1,-80)cCon.Position=UDim2.new(0,0,0,80)cCon.BackgroundTransparency=1 cCon.Parent=main
local sF=Instance.new'ScrollingFrame'sF.Size=UDim2.new(1,0,1,0)sF.BackgroundTransparency=1 sF.BorderSizePixel=0 sF.ScrollBarThickness=6 sF.ScrollBarImageColor3=Color3.new(0,1,0)sF.Parent=cCon
local tabs={}for i=1,3 do local sc=Instance.new'ScrollingFrame'sc.Size=UDim2.new(1,0,1,0)sc.BackgroundTransparency=1 sc.BorderSizePixel=0 sc.ScrollBarThickness=5 sc.ScrollBarImageColor3=Color3.new(0,1,0)sc.Visible=(i==1)sc.Parent=sF tabs[i]=sc end
local function addBtn(p,y,t,cb)local b=Instance.new'TextButton'b.Size=UDim2.new(.92,0,0,40)b.Position=UDim2.new(.04,0,0,y)b.BackgroundColor3=Color3.new(0,.15,0)b.BorderSizePixel=2 b.BorderColor3=Color3.new(0,.8,0)b.Text=t b.TextColor3=Color3.new(1,1,1)b.TextSize=14 b.Font=Enum.Font.GothamSemibold b.Parent=p b.MouseButton1Click:Connect(cb)return 50 end
local function addTgl(p,y,t,st,cb)local b=Instance.new'TextButton'b.Size=UDim2.new(.92,0,0,40)b.Position=UDim2.new(.04,0,0,y)b.BackgroundColor3=st and Color3.new(0,.35,0)or Color3.new(.12,.12,.12)b.BorderSizePixel=2 b.BorderColor3=Color3.new(0,.8,0)b.Text=t..(st and" ✅ ON"or" ❌ OFF")b.TextColor3=Color3.new(1,1,1)b.TextSize=14 b.Font=Enum.Font.GothamSemibold b.Parent=p local s=st b.MouseButton1Click:Connect(function()s=not s b.BackgroundColor3=s and Color3.new(0,.35,0)or Color3.new(.12,.12,.12)b.Text=t..(s and" ✅ ON"or" ❌ OFF")cb(s)end)return 50 end
local yh=15
local nb=Instance.new'TextBox'nb.Size=UDim2.new(.92,0,0,40)nb.Position=UDim2.new(.04,0,0,yh)nb.BackgroundColor3=Color3.new(.08,.08,.08)nb.BorderSizePixel=2 nb.BorderColor3=Color3.new(0,.8,0)nb.Text=""nb.PlaceholderText="✏️ اكتب جزءاً من اسم اللاعب..."nb.TextColor3=Color3.new(1,1,1)nb.TextSize=14 nb.Font=Enum.Font.GothamSemibold nb.Parent=tabs[1]yh=yh+50
local iF=Instance.new'Frame'iF.Size=UDim2.new(0,55,0,55)iF.Position=UDim2.new(.04,0,0,yh)iF.BackgroundColor3=Color3.new(.06,.06,.06)iF.BorderSizePixel=2 iF.BorderColor3=Color3.new(0,.8,0)iF.Parent=tabs[1]
targetImageLabel=Instance.new'ImageLabel'targetImageLabel.Size=UDim2.new(1,-6,1,-6)targetImageLabel.Position=UDim2.new(0,3,0,3)targetImageLabel.BackgroundTransparency=1 targetImageLabel.Image="rbxassetid://0"targetImageLabel.ImageColor3=Color3.new(.8,.8,.8)targetImageLabel.Parent=iF
local lkB=Instance.new'TextButton'lkB.Size=UDim2.new(.45,0,0,40)lkB.Position=UDim2.new(.25,0,0,yh+8)lkB.BackgroundColor3=Color3.new(0,.28,0)lkB.BorderSizePixel=2 lkB.BorderColor3=Color3.new(0,.8,0)lkB.Text="🔒 قفل"lkB.TextColor3=Color3.new(1,1,1)lkB.TextSize=14 lkB.Font=Enum.Font.GothamBold lkB.Parent=tabs[1]
local ulkB=Instance.new'TextButton'ulkB.Size=UDim2.new(.45,0,0,40)ulkB.Position=UDim2.new(.72,0,0,yh+8)ulkB.BackgroundColor3=Color3.new(.28,0,0)ulkB.BorderSizePixel=2 ulkB.BorderColor3=Color3.new(.8,0,0)ulkB.Text="🔓 فك"ulkB.TextColor3=Color3.new(1,1,1)ulkB.TextSize=14 ulkB.Font=Enum.Font.GothamBold ulkB.Parent=tabs[1]yh=yh+65
local stL=Instance.new'TextLabel'stL.Size=UDim2.new(.92,0,0,25)stL.Position=UDim2.new(.04,0,0,yh)stL.BackgroundTransparency=1 stL.Text="🔒 الهدف: لا يوجد"stL.TextColor3=Color3.new(0,1,0)stL.TextSize=13 stL.Font=Enum.Font.GothamSemibold stL.Parent=tabs[1]yh=yh+35
yh=yh+addBtn(tabs[1],yh,"✨ الانتقال للهدف",teleport)yh=yh+addBtn(tabs[1],yh,"🚶 السير للهدف",walk)
lkB.MouseButton1Click:Connect(function()local p=nb.Text if p==""then game:service'StarterGui':SetCore("SendNotification",{Title="خطأ",Text="أدخل اسم اللاعب",Duration=2})return end local t=findPlayer(p)if t then lockedTarget=t targetImageLabel.Image=getAvatar(t.UserId)targetImageLabel.ImageColor3=Color3.new(1,1,1)stL.Text="🔒 الهدف: "..t.Name game:service'StarterGui':SetCore("SendNotification",{Title="✅ تم القفل",Text=t.Name,Duration=2})else game:service'StarterGui':SetCore("SendNotification",{Title="❌ خطأ",Text="لا يوجد لاعب",Duration=2})end end)
ulkB.MouseButton1Click:Connect(function()lockedTarget=nil targetImageLabel.Image="rbxassetid://0"targetImageLabel.ImageColor3=Color3.new(.6,.6,.6)stL.Text="🔒 الهدف: لا يوجد"game:service'StarterGui':SetCore("SendNotification",{Title="🔓 فك القفل",Text="عودة للوضع العادي",Duration=2})end)
coroutine.wrap(function()while true do if lockedTarget then stL.Text="🔒 الهدف: "..(lockedTarget.DisplayName or lockedTarget.Name)else stL.Text="🔒 الهدف: لا يوجد"end wait(1)end end)()
tabs[1].CanvasSize=UDim2.new(0,0,0,yh+20)
local yc=15 yc=yc+addTgl(tabs[2],yc,"🎯 Aim Bot",aimbotActive,function(v)aimbotActive=v end)yc=yc+addBtn(tabs[2],yc,"🏃 سرعة 100",function()currentSpeed=100 apply()end)yc=yc+addBtn(tabs[2],yc,"🏃 سرعة 50",function()currentSpeed=50 apply()end)yc=yc+addBtn(tabs[2],yc,"🏃 سرعة عادية",function()currentSpeed=16 apply()end)yc=yc+addBtn(tabs[2],yc,"🦘 قفز 200",function()currentJump=200 apply()end)yc=yc+addBtn(tabs[2],yc,"🦘 قفز 100",function()currentJump=100 apply()end)yc=yc+addBtn(tabs[2],yc,"🦘 قفز عادي",function()currentJump=50 apply()end)
tabs[2].CanvasSize=UDim2.new(0,0,0,yc+20)
local ys=15 ys=ys+addBtn(tabs[3],ys,"💬 سيرفر الديسكورد",function()setclipboard("https://discord.gg/a8KaMAjbN")game:service'StarterGui':SetCore("SendNotification",{Title="تم النسخ",Text="رابط الديسكورد في الحافظة",Duration=2})end)ys=ys+addBtn(tabs[3],ys,"🛑 تعطيل الكل",function()aimbotActive=false lockedTarget=nil targetImageLabel.Image="rbxassetid://0"stL.Text="🔒 الهدف: لا يوجد"end)
tabs[3].CanvasSize=UDim2.new(0,0,0,ys+20)
local tN={"🏠 الرئيسية","⚔️ القتال","⚙️ الإعدادات"},tB={}for i,n in ipairs(tN)do local b=Instance.new'TextButton'b.Size=UDim2.new(0,125,1,0)b.Position=UDim2.new(0,(i-1)*125,0,0)b.BackgroundColor3=(i==1)and Color3.new(0,.3,0)or Color3.new(0,.1,0)b.BorderSizePixel=2 b.BorderColor3=Color3.new(0,.8,0)b.Text=n b.TextColor3=Color3.new(
  
