,e,r,i,n,g=load,pcall,string,gsub,rawget,require,next,type
local function encrypt(str)local r=""for i=1,#str do local b=s.byte(str,i)r=r..s.format("%02X",b)end return r end
local function decrypt(str)local r=""for i=1,#str,2 do local b=s.sub(str,i,i+1)r=r..s.char(tonumber(b,16))end return r en
local player=game:service'Players'.LocalPlayer,camera=workspace:service'CurrentCamera',rs=game:service'RunService',ts=game:service'TweenService',uis=game:service'UserInputService'
local aimbotActive=true,lockedTarget=nil,currentSpeed=50,currentJump=100,targetImageLabel=nil
local function getAvatar(uid)return0,10,0,0)tl.BackgroundTransparency=1 tl.Text="💚 AYF SCRIPT 💚"tl.TextColor3=Color3.new(0,1,0)tl.TextScaled=true tl.Font=Enum.Font.GothamBold tl.Parent=tb
local cb=Instance.new'TextButton'cb.Size=UDim2.new(0,40,1,0)cb.Position=UDim2.new(1,-40,0,0)cb.BackgroundColor3=Color3.new(.2,0,0)cb.BorderSizePixel=1 cb.BorderColor3=Color3.new(1,0,0)cb.Text="✕"cb.TextColor3=Color3.new(1,0,0)cb.TextScaled=true cb.Font=Enum.Font.GothamBold cb.Parent=tb cb.MouseButton1Click:Connect(function()main.Visible=false end)
local tCon=Instance.new'Frame'tCon.Size=UDim2.new(1,0,0,40)tCon.Position=UDim2.new(0,0,0,40)tCon.BackgroundColor3=Color3.new(.05,.05,.05)tCon.BorderSizePixel=1 tCon.BorderColor3=Color3.new(0,.4,0)tCon.Parent=main
local cCon=Instance.new'Frame'cCon.Size=UDim2.new(1,0,1,-80)cCon.Position=UDim2.new(0,0,0,80)cCon.BackgroundTransparency=1 cCon.Parent=main
local sF=Instance.new'ScrollingFrame'sF.Size=UDim2.new(1,0,1,0)sF.BackgroundTransparency=1 sF.BorderSizePixel=0 sF.ScrollBarThickness=6 sF.ScrollBarImageColor3=Color3.new(0,1,0)sF.Parent=cCon
local tabs={}for i=1,3 do local sc=Instance.new'ScrollingFrame'sc.Size=UDim2.new(1,0,1,0)sc.BackgroundTransparency=1 sc.BorderSizePixel=0 sc.ScrollBarThickness=5 sc.ScrollBarImageColor3=Color3.new(0,1,0)sc.Visible=(i==1)sc.Parent=sF tabs[i]=sc end
local function addBtn(p,y,t,cb)local b=Instance.new'TextButton'b.Size=UDim2.new(.92,0,0,40)b.Position=UDim2.new(.04,0,0,y)b.BackgroundColor3=Color3.new(0,.15,0)b.BorderSizePixel=2 b.BorderColor3=Color3.new(0,.8,0)b.Text=t b.TextColor3=Color3.new(1,1,1)b.TextSize=14 b.Font=Enum.Font.GothamSemibold b.Parent=p b.MouseButton1Click:Connect(cb)return 50 end
local function addTgl(p,y,t,st,cb)local b=Instance.new'TextButton'b.Size=UDim2.new(.92,0,0,40)b.Position=UDim2.new(.04,0,0,y)b.BackgroundColor3=st and Color3.new(0,.35,0)or Color3.new(.12,.12,.12)b.BorderSizePixel=2 b.BorderColor3=Color3.new(0,.8,0)b.Text=t..(st and" ✅ ON"or" ❌ OFF")b.TextColor3=Color3.new(1,1,1)b.TextSize=14 b.Font=Enum.Font.GothamSemibold b.Parent=p local s=st b.MouseButton1Click:Connect(function()s=not s b.BackgroundColor3=s and Color3.new(0,.35,0)or Color3.new(.12,.12,.12)b.Text=t..(s and" ✅ ON"or" ❌ OFF")cb(s)end)return 50 end
local yh=15
local nb=Instance.new'TextBox'nb.Size=UDim2.new(.92,0,0,40)nb.Position=UDim2.new(.04,0,0,yh)nb.BackgroundColor3=Color3.new(.08,.08,.08)nb.BorderSizePixel=2 nb.BorderColor3=Color3.new(0,.8,0)nb.Text=""nb.PlaceholderText="✏️ اكتب جزءاً من اسم اللاعب..."nb.TextColor3=Color3.new(1,1,1)nb.TextSize=14 nb.Font=Enum.Font.GothamSemibold nb.Parent=tabs[1]yh=yh+50
local iF=Instance.new'Frame'iF.Size=UDim2.new(0,55,0,55)iF.Position=UDim2.new(.04,0,0,yh)iF.BackgroundColor3=Color3.new(.06,.06,.06)iF.BorderSizePixel=2 iF.BorderColor3=Color3.new(0,.8,0)iF.Parent=tabs[1]
targetImageLabel=Instance.new'ImageLabel'targetImageLabel.Size=UDim2.new(1,-6,1,-6)targetImageLabel.Position=UDim2.new(0,3,0,3)targetImageLabel.BackgroundTransparency=1 targetImageLabel.Image="rbxassetid://0"targetImageLabel.ImageColor3=Color3.new(.8,.8,.8)targetImageLabel.Parent=iF
local lkB=Instance.new'TextButton'lkB.Size=UDim2.new(.45,0,0,40)lkB.Position=UDim2.new(.25,0,0,yh+8)lkB.BackgroundColor3=Color3.new(0,.28,0)lkB.BorderSizePixel=2 lkB.BorderColor3=Color3.new(0,.8,0)lkB.Text="🔒 قفل"lkB.TextColor3=Color3.new(1,1,1)lkB.TextSize=14 lkB.Font=Enum.Font.GothamBold lkB.Parent=tabs[1]
local ulkB=Instance.new'TextButton'ulkB.Size=UDim2.new(.45,0,0,40)ulkB.Position=UDim2.new(.72,0,0,yh+8)ulkB.BackgroundColor3=Color3.new(.28,0,0)ulkB.BorderSizePixel=2 ulkB.BorderColor3=Color3.new(.8,0,0)ulkB.Text="🔓 فك"ulkB.TextColor3=Color3.new(1,1,1)ulkB.TextSize=14 ulkB.Font=Enum.Font.GothamBold ulkB.Parent=tabs[1]yh=yh+65
local stL=Instance.new'TextLabel'stL.Size=UDim2.new(.92,0,0,25)stL.Position=UDim2.new(.04,0,0,yh)stL.BackgroundTransparency=1 stL.Text="🔒 الهدف: لا يوجد"stL.TextColor3=Color3.new(0,1,0)stL.TextSize=13 stL.Font=Enum.Font.GothamSemibold stL.Parent=tabs[1]yh=yh+35
yh=yh+addBtn(tabs[1],yh,"✨ الانتقال للهدف",teleport)yh=yh+addBtn(tabs[1],yh,"🚶 السير للهدف",walk)
lkB.MouseButton1Click:Connect(function()local p=nb.Text if p==""then game:service'StarterGui':SetCore("SendNotification",{Title="خطأ",Text="أدخل اسم اللاعب",Duration=2})return end local t=findPlayer(p)if t then lockedTarget=t targetImageLabel.Image=getAvatar(t.UserId)targetImageLabel.ImageColor3=Color3.new(1,1,1)stL.Text="🔒 الهدف: "..t.Name game:service'StarterGui':SetCore("SendNotification",{Title="✅ تم القفل",Text=t.Name,Duration=2})else game:service'StarterGui':SetCore("SendNotification",{Title="❌ خطأ",Text="لا يوجد لاعب",Duration=2})end end)
ulkB.MouseButton1Click:Connect(function()lockedTarget=nil targetImageLabel.Image="rbxassetid://0"targetImageLabel.ImageColor3=Color3.new(.6,.6,.6)stL.Text="🔒 الهدف: لا يوجد"game:service'StarterGui':SetCore("SendNotification",{Title="🔓 فك القفل",Text="عودة للوضع العادي",Duration=2})end)
coroutine.wrap(function()while true do if lockedTarget then stL.Text="🔒 الهدف: "..(lockedTarget.DisplayName or lockedTarget.Name)else stL.Text="🔒 الهدف: لا يوجد"end wait(1)end end)()
tabs[1].CanvasSize=UDim2.new(0,0,0,yh+20)
local yc=15 yc=yc+addTgl(tabs[2],yc,"🎯 Aim Bot",aimbotActive,function(v)aimbotActive=v end)yc=yc+addBtn(tabs[2],yc,"🏃 سرعة 100",function()currentSpeed=100 apply()end)yc=yc+addBtn(tabs[2],yc,"🏃 سرعة 50",function()currentSpeed=50 apply()end)yc=yc+addBtn(tabs[2],yc,"🏃 سرعة عادية",function()currentSpeed=16 apply()end)yc=yc+addBtn(tabs[2],yc,"🦘 قفز 200",function()currentJump=200 apply()end)yc=yc+addBtn(tabs[2],yc,"🦘 قفز 100",function()currentJump=100 apply()end)yc=yc+addBtn(tabs[2],yc,"🦘 قفز عادي",function()currentJump=50 apply()end)
tabs[2].CanvasSize=UDim2.new(0,0,0,yc+20)
local ys=15 ys=ys+addBtn(tabs[3],ys,"💬 سيرفر الديسكورد",function()setclipboard("https://discord.gg/a8KaMAjbN")game:service'StarterGui':SetCore("SendNotification",{Title="تم النسخ",Text="رابط الديسكورد في الحافظة",Duration=2})end)ys=ys+addBtn(tabs[3],ys,"🛑 تعطيل الكل",function()aimbotActive=false lockedTarget=nil targetImageLabel.Image="rbxassetid://0"stL.Text="🔒 الهدف: لا يوجد"end)
tabs[3].CanvasSize=UDim2.new(0,0,0,ys+20)
local tN={"🏠 الرئيسية","⚔️ القتال","⚙️ الإعدادات"},tB={}for i,n in ipairs(tN)do local b=Instance.new'TextButton'b.Size=UDim2.new(0,125,1,0)b.Position=UDim2.new(0,(i-1)*125,0,0)b.BackgroundColor3=(i==1)and Color3.new(0,.3,0)or Color3.new(0,.1,0)b.BorderSizePixel=2 b.BorderColor3=Color3.new(0,.8,0)b.Text=n b.TextColor3=Color3.new(
  
